### ISSUE TITLE
can't see my files from vlc

### ISSUE THREAD

**Issue by mokas01** [YunoHost-Apps/minidlna_ynh#6]
i'm running minidlna on my server, it seem to be working, but i can't see the files in the yunohost.multimedia/share folder.
The port seem to be opened in the firewall, and on the routeur
Upnp seem to be disabled and i can't activate it, i don't know if it is related

Yunohost is running on an ARM board (olimex) and on Stretch 3.0 beta 5

Thanks for your help

**Comment by maniackcrudelis** [comment]
Can you try with another software/device than VLC ?
I encountered some issues with VLC sometimes without be able to explain why.

Also, this app hasn't been tested on Stretch before you I think.
I guess that your minidlna version is 1.1.6 ?

**Comment by mokas01** [comment]
I tried from several software (Rythmbox & Totem with grilo plugin installed) and i still can't see nothing.
Any idea where i could look for more info ?
Yes, i have minidlna 1.1.6 

I'm more than happy to help you and test whatever you suggest/think could work on stretch

Thanks for your help

**Comment by maniackcrudelis** [comment]
Can you have a look to the log of minidlna, `/var/log/minidlna.log` or from the admin panel.

**Comment by mokas01** [comment]
its quite empty (4 lines to say it started and listen on port 48200…)

**Comment by maniackcrudelis** [comment]
OK, so I guess that minidlna doesn't receive any connection from your clients.
Maybe though, you can make your log more verbose by turning your log level at "debug" in the config file /etc/minidlna.conf.

**Comment by mokas01** [comment]
agreed… I just don't understand why… nor where it is blocked. I forwarded all existing ports on the single server I have on my router, and yunohost firewall list shows 48200 as open. I can't find a log showing where it blocks… you might want to close the issue, as it is not clear it is related to the app… I just don't know where to look

**Comment by maniackcrudelis** [comment]
Actually, you don't need to open this port on your router, and it's better to don't. DLNA is intended to work only on local network.
Anyway, turning your log to "debug" may help us to see more information about what happens.

**Comment by mokas01** [comment]
nope :/
https://paste.yunohost.org/moluxilehu

as for the router port, i closed it, just to be sure it wasn't interfering

**Comment by maniackcrudelis** [comment]
The package minidlna for YunoHost is probably not the problem here. Minidlna can be capricious sometimes...
Could you stop minidlna, remove its database (`/var/cache/minidlna/files.db`) and restart minidlna, the log should then show if there's any problem with your files.

**Comment by mokas01** [comment]
ok, my bad. the debug argument wasn't acknoledged. 
Here is a log with Debug set : 
https://paste.yunohost.org/kesowatosu

good news is : the system sees incoming connexion. Bad news is : my clients still see no answer, even if I have multiple files. Is there a way to check if upnp:rootdevice given as an answer to each request is pointing to the right folder ?

Thanks again for the help

**Comment by maniackcrudelis** [comment]
Ok, in this log I can't see any files added to the database.
Did you remove the file `/var/cache/minidlna/files.db` before restarting minidlna ?

If yes, please have a quick look to the file ?
It's not really readable, as it's a sqlite database, but still, you could find some of your media files in it.

**Comment by mokas01** [comment]
Yes, sorry i didn'n notice the log had been archived and the new one didn't have it
https://paste.yunohost.org/pikiyicako
Here you can see the database is being created. Opening the DB, I can see traces of my files. At lears names and locations on the system

**Comment by maniackcrudelis** [comment]
Can you show me your config file `/etc/minidlna.conf` please ?

**Comment by mokas01** [comment]
I don't think I changed much but here it is
https://paste.yunohost.org/ugasigijuw

**Comment by maniackcrudelis** [comment]
Ok, and nothing better either with your clients I guess ?

**Comment by mokas01** [comment]
I see that VLC has an error with libupnp (before sending any request), but in Kodi's log, i can't see much… if you want to have a look : 
https://paste.yunohost.org/gijubiriyo.scala

**Comment by mokas01** [comment]
i found the issue. Nothing related to minidlna nor yunohost, but to a stupid firewall rule I didn't remember having set on my computer. Thanks for your help, sorry for the noise

**Comment by mokas01** [comment]
i found the issue. Nothing related to minidlna nor yunohost, but to a stupid firewall rule I didn't remember having set on my computer. Thanks for your help, sorry for the noise

**Comment by maniackcrudelis** [comment]
Oh ok !
So I'm relieved because I had no more idea about how to fix that !
