### ISSUE TITLE
Commit is not up to date in the community.json

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/minidlna_ynh#9]
Hellow,

I found that the commit on [community.json](https://github.com/YunoHost/apps/blob/master/community.json) is outdated, hence people installing the app via this list won't benefit from the last upgrades / improvements ...

Please create a PR to update it on the list (I do not maintain this app so it's not relevant for me to do it and it might be refused...)

ProTip™ : possibly you can now set the commit to 'HEAD', to use the latest commit of master automatically in the future. If you do this, it is strongly recommended to use a 'testing' branch for changes that are not deemed stable yet.

**Comment by maniackcrudelis** [comment]
I know ;)
Just a fix for package check on arm, that's all.

**Comment by alexAubin** [comment]
Uh but didnt you upgrade the helpers ? :o

**Comment by maniackcrudelis** [comment]
Oh, so you're really behind those issues !? I thought it was an automatic issue ;)

Actually, I upgraded my common.sh, which is common to all my apps. That's why my helpers were upgraded in the commit.
But, I you prefer, I can update to HEAD for this app as well as other apps.

**Comment by alexAubin** [comment]
Uh okay, I dunno it just looked like you made some fixes (but maybe you just updated helpers which are not actually used by this app if i understand correctly ?)

Anyway you seem to know what you're doing so I guess we can close the issue ¯\\\_(ツ)\_/¯
